name: Daily restricted wallets update

on:
  schedule:
    - cron: "15 9 * * *" # Runs every day
  workflow_dispatch:

jobs:
  update-restricted:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download new restricted file
        run: |
          if curl -o new-restricted.json https://raw.githubusercontent.com/teia-community/teia-report/main/restricted.json; then
            echo "download successful."
          else
            echo "download failed."
            exit 1
          fi

      - name: Check File Size
        id: check-file
        run: |
          if [ -s new-restricted.json ]; then
            echo "File is not empty."
          else
            echo "File is empty."
            exit 1
          fi

      - name: Check for Differences
        id: check-differences
        run: |
          if ! diff -q new-restricted.json restricted.json; then
            echo "Files are different."
            echo "DIFFERENT_FILE=true" >> $GITHUB_ENV
          else
            echo "Files are the same. Skipping commit."
            echo "DIFFERENT_FILE=false" >> $GITHUB_ENV
          fi

      - name: Overwrite File
        if: steps.check-file.outcome == 'success' && env.DIFFERENT_FILE == 'true'
        run: |
          mv new-restricted.json restricted.json

      - name: Commit and Push Changes
        if: steps.check-file.outcome == 'success' && env.DIFFERENT_FILE == 'true'
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "actions@github.com"

          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-file-$timestamp"

          git checkout -b "$branch_name"

          git add restricted.json

          git commit -m "Update restricted wallets"

          git push origin "$branch_name"

          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main

          # delete the temporary branch
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"
